### PR TITLE
Fixed ask_block_contact and ask_unblock_contact

### PR DESCRIPTION
**Pull request by adbenitez**
Just removed the "calls" stuff and fixed some previous accidental removal while trying to fix this same issue.

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Make a PR to the upstream repo instead.

**Comment by adbenitez** [comment]
the upstream repo have several differences with this one :(

**Comment by adbenitez** [comment]
I mean the strings.xml is different to this one

**Comment by adbenitez** [comment]
done

**Comment by ralphtheninja** [comment]
> the upstream repo have several differences with this one :(

The upstream is the canonical one.

**Pull request closed without merging**
